/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ap-southeast-1",
  "aws_cognito_identity_pool_id": "ap-southeast-1:289b0d35-9dd6-4164-a2f8-073a72d88e84",
  "aws_cognito_region": "ap-southeast-1",
  "aws_user_pools_id": "ap-southeast-1_c0EMF4obI",
  "aws_user_pools_web_client_id": "1cjpg4lfnim8m1p7iiokcvbrld",
  "oauth": {
    "domain": "prostylee-dev.auth.ap-southeast-1.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "prostylee://oauth",
    "redirectSignOut": "prostylee://signout",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
