/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ap-northeast-2",
  "aws_cognito_identity_pool_id": "ap-northeast-2:6f692db3-8d7b-4f30-8572-4e2e9ca8deb3",
  "aws_cognito_region": "ap-northeast-2",
  "aws_user_pools_id": "ap-northeast-2_rW0NZTnuq",
  "aws_user_pools_web_client_id": "780jet4be4koug09joui82mlo2",
  "oauth": {
    "domain": "prostylee-staging.auth.ap-northeast-2.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "prostylee://",
    "redirectSignOut": "prostylee://",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_appsync_graphqlEndpoint": "https://mwxnyqpmxfgappfykgbcfxf5dm.appsync-api.ap-northeast-2.amazonaws.com/graphql",
  "aws_appsync_region": "ap-northeast-2",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_appsync_apiKey": "da2-dccamjchtvfp7kopuciswnvnty",
  "aws_user_files_s3_bucket": "psmedia214808-staging",
  "aws_user_files_s3_bucket_region": "ap-northeast-2"
};
export default awsmobile;