import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '$white',
    flexDirection: 'column',
    paddingTop: 18,
    paddingBottom: 32,
  },
  viewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingRight: 16,
    paddingBottom: 16,
  },
  viewBody: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingRight: 16,
  },
  viewCredit: {
    flex: 1,
    borderRightWidth: 1,
    borderColor: '#E9EAEB',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewCoupon: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewTemp: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    flex: 1,
  },

  viewCheckout: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },

  btnCredit: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
  },
  btnCoupon: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
  },
  btnCheckout: {
    flex: 1,
  },
  labelCredit: {
    color: '$black',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flex: 1,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  labelCoupon: {
    color: '$black',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  viewTempTitle: {
    color: '#8B9399',
    fontSize: 13,
    lineHeight: 18,
  },
  viewTempValue: {
    color: '#333333',
    fontSize: 16,
    lineHeight: 24,
  },
  wrapChip: {
    backgroundColor: 'transparent',
    padding: 0,
    margin: 0,
  },
  chipText: {
    color: '$purple',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  couponText: {
    color: '$purple',
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 18,
  },
});
